### ISSUE TITLE
Code review. Round 2

### ISSUE THREAD

**Issue by oblalex** [YuriiM/JBSRepo#2]
У нас накопился следующий ряд вопросов:

- [x] Пока всё ещё отсутствует инструкция, как поднять проект с нуля. Например, надо как-то знать, что для `psycopg2` нужно поставить пакет `postgresql-server-dev` или его аналог. И т.д. вплоть до запуска проекта в браузере.
- [x] В догонку к предыдущему пункту: на какой версии питона всё же можно выполнять проверки? Ранее были указаны версии 3.х, сегодня уже есть 2.7 и 3.4, но в коде изменений по этому поводу нет. Это тоже должно быть зафиксировано в инструкции.
- [x] Ограничение на размер загружаемых изображений: http://git.io/NujI. Хотелось бы знать, откуда взялось само ограничение. В задании этого нет, а в описании проекта об этом ничего не сказано. Так же хотелось бы знать, почему макс. размер прописан в коде, а не вынесен в настройки?
- [x] В проекте кругом наблюдается хардкод ссылок. Надо использовать `reverse` в коде и `{% url ... %}` в шаблонах.
- [x] Почему здесь http://git.io/NXBC используются имена моделей вместо самих моделей? Ведь, во-первых, имя модели модели может измениться, а во-вторых, модели с такими именами могут существовать в других приложениях и тогда фильтрация будет работать неправильно.
- [x] В middleware наблюдается аномальное кол-во отступов: http://git.io/NzA7. Об этом даже сообщается в отчете landscape.io. Это нужно исправить.
- [x] Во многих файлах отсутствует пустая строка в конце файла. Даже github указывает на это в diff-ах: https://github.com/YuriiM/JBSRepo/compare/initial...round-1
- [x] Мы точно видели у тебя IDE для питона, но почему-то ".idea" отсутствует в ".gitignore". Странно, что её там нет и странно, что при этом такая папка не попала в репозиторий.
- [x] В описании проекта указано, что поддерживается питон 2.7, но по меркам 2-го питона middleware объявлен как old-style класс. Это может иметь последствия, и landscape.io так же об этом говорит.
- [x] Нас очень заинтересовали вьюхи, в частности `edit`. Вместо http://git.io/Ngvt нам бы хотелось увидеть использование декоратора `login_required`, а так же соответстующего декоратора вместо этого http://git.io/NgvH. Вообще, передача параметров выглядит странно, особенно `success`: http://git.io/Ngfa. Нам бы хотелось увидеть использование CBVs вместо FBVs для всех вьюх. Вьюху `logout` можно оставить как FBV.

И напоследок, пожелание: отчетами от разных анализаторов надо пользоваться :wink:

**Comment by YuriiM** [comment]
__п2.__ С версиями немного напутал. Выполнять проверки можно на версиях 2.7, 3.3, 3.4.
__п3.__ Создание ограничения было моей инициативой. Максимальный размер вынес в настройки (aabbd4d).
__п10.__ В случае [```arguments['success'] = 1```](https://github.com/YuriiM/JBSRepo/blob/master/tasks/views.py#L73) в шаблоне [image_upload.html](https://github.com/YuriiM/JBSRepo/blob/master/tasks/templates/tasks/image_upload.html#L14-21) идет проверка на существование переменной ```success```. Если такая существует - выдать пользователю определенное сообщение. Данный способ использовал дабы не смешивать back-end с front-end'ом, ведь передавать в представлении кусок текста, которому явно место в шаблоне - не очень хорошо.

**Comment by oblalex** [comment]
Добавлю сюда ссылку для удобства: https://github.com/YuriiM/JBSRepo/compare/round-1...round-2

**Comment by oblalex** [comment]
>  в шаблоне image_upload.html идет проверка на существование переменной `success`
так а почему бы не использовать `True` вместо `1`?
